### ISSUE TITLE
Could add quotes around speech

### ISSUE THREAD

**Issue by Gragt** [weijia-cheng/epictetus_short-works_george-long#2]
Consider adding quotes around speech, .e.g, Encheiridion, line 117: Woe to me. Probably not that important given the nature of the text, but it could help readers.

**Comment by weijia-cheng** [comment]
Yeah, I did notice this sometimes in the text. I guess we have a precedent for changing that sort of thing with _Gil Blas_ now, but in this case I don't think it ever particularly hindered readability. I don't really think it is worth the effort and the editorializing in this case.
