### ISSUE TITLE
Possible long description tweaks

### ISSUE THREAD

**Issue by Gragt** [weijia-cheng/epictetus_short-works_george-long#4]
I know the long description is recycled from a previous book. Still, I wonder if we should not change “friendly with emperors” to “favoured by emperors” or something to that effect.

I’d also leave the th of 18th as regular script instead of superscript.

**Comment by weijia-cheng** [comment]
Tweaked in 50b2906.

**Comment by Gragt** [comment]
I saw you changed more parts. I also thought of modifying those but I focused on the part I found the most egregious. It does read better now!
